# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Github secrets demo

on:
  workflow_dispatch:

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v2
      - name: Demo of secret
        env: 
          NAME_SECRET: ${{ secrets.NAME }}
        if:  env.NAME_SECRET == 'Ankit'
        run: echo "I know what the secret is!"
 
